package insertTicket;

public enum EnumValidation 
{	
	VALIDATETICKETID,	
	VALIDATEDESCRIPTION,
	VALIDATEEXPECTEDENDDATE,
	VALIDATEREPORTERID,
	VALIDATEEMPLOYEEID,
	VALIDATEASSIGNEENAME,
	VALIDATETICKETTYPE,
	VALIDATETICKETSTATUS,
	VALIDATEPRIORITY,
	VALIDATEIMPACT,
	VALIDATEURGENCY,
	VALIDATECUSTOMERID,
	VALIDATECUSTOMERNAME,
	VALIDATETICKETLEVEL,
	VALIDATECREATORID,
	VALIDATECREATORNAME	     
}